/* generated by scripts/tauri-build.js */
const http = require('http');
const next = require('next');

const dir = process.cwd(); // set by Tauri to the resources directory
const dev = false;
const port = process.env.PORT || 3000;

const app = next({ dev, dir });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  http.createServer((req, res) => handle(req, res)).listen(port, () => {
    console.log('[tauri-server] Next app listening on port ' + port);
  });
}).catch((err) => {
  console.error('[tauri-server] Failed to start Next app', err);
  process.exit(1);
});
