/* eslint-disable */
'use strict';
// Tauri build helper for server-mode Next.js (no static export).
// - Runs a production Next build (regular .next output, no standalone symlinks)
// - Writes a tiny Node launcher to src-tauri/resources/server.js
// - Copies the current Node.js binary into src-tauri/resources/node so it is bundled

const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const cwd = process.cwd();

function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function run(cmd, args, opts = {}) {
  const bin = process.platform === 'win32' ? `${cmd}.cmd` : cmd;
  const res = spawnSync(bin, args, { stdio: 'inherit', shell: true, ...opts });
  if (res.status !== 0) {
    throw new Error(`${cmd} ${args.join(' ')} failed with code ${res.status ?? 1}`);
  }
}

(function main() {
  // 1) Build Next in production (regular .next output)
  // Ensure we do not attempt static export
  delete process.env.TAURI_STATIC_EXPORT;

  run('pnpm', ['build'], { env: { ...process.env, NODE_ENV: 'production' } });

  // Validate build artifacts
  const nextDir = path.join(cwd, '.next');
  const staticDir = path.join(nextDir, 'static');
  if (!fs.existsSync(nextDir)) {
    throw new Error('[tauri-build] .next not found after build.');
  }
  if (!fs.existsSync(staticDir)) {
    throw new Error('[tauri-build] .next/static not found after build.');
  }

  // 2) Write server launcher used by the desktop app to start Next
  const serverLauncher = `/* generated by scripts/tauri-build.js */
const http = require('http');
const next = require('next');

const dir = process.cwd(); // set by Tauri to the resources directory
const dev = false;
const port = process.env.PORT || 3000;

const app = next({ dev, dir });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  http.createServer((req, res) => handle(req, res)).listen(port, () => {
    console.log('[tauri-server] Next app listening on port ' + port);
  });
}).catch((err) => {
  console.error('[tauri-server] Failed to start Next app', err);
  process.exit(1);
});
`;
  const serverOut = path.join(cwd, 'src-tauri', 'resources', 'server.js');
  ensureDir(path.dirname(serverOut));
  fs.writeFileSync(serverOut, serverLauncher, 'utf8');
  console.log(`[tauri-build] Wrote server launcher -> ${serverOut}`);

  // 3) Bundle the current Node.js runtime into resources for the app to spawn
  const nodeSrc = process.execPath; // Path to the Node running this script
  const isWin = process.platform === 'win32';
  const nodeDest = path.join(cwd, 'src-tauri', 'resources', 'node', isWin ? 'node.exe' : 'node');
  try {
    copyFile(nodeSrc, nodeDest);
    // Make sure it's executable on unix
    if (!isWin) {
      try { fs.chmodSync(nodeDest, 0o755); } catch {}
    }
    console.log(`[tauri-build] Bundled Node runtime -> ${nodeDest}`);
  } catch (e) {
    console.warn('[tauri-build] Failed to copy Node runtime, the system Node will be used at runtime if available.', e);
  }
})();
